/* Body file for function Component3
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "component3.h"
//#include <stdio.h>

asn1SccT_FunctionStatus component3_buildStatus()
{
    asn1SccT_FunctionStatus functionStatus;
    functionStatus.id = PID_component3;
    functionStatus.error_count = 0;
    functionStatus.state = T_FunctionStatus_state_offline;

    return functionStatus;
}

void component3_startup(void)
{

}

void component3_PI_trigger3(void)
{
   asn1SccT_FunctionStatus functionStatus = component3_buildStatus();

   component3_RI_WriteStatus(&functionStatus);
}


