/* Body file for function DataStructure
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "datastructure.h"

static asn1SccT_FunctionStatus functionStatuses[PID_env];

void datastructure_startup(void)
{
}

void datastructure_PI_ReadStatus
      (const asn1SccPID *IN_pid,
       asn1SccT_FunctionStatus *OUT_functionstatus)

{
   *OUT_functionstatus = functionStatuses[*IN_pid];
}


void datastructure_PI_WriteStatus
      (const asn1SccT_FunctionStatus *IN_functionstatus)

{
   functionStatuses[IN_functionstatus->id] = *IN_functionstatus;
}


