/* Body file for function Environment
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/

#include "environment.h"
#include "logs.h"

#include <time.h>
#include <unistd.h>

#define CUC_TIME_ARRAY_SIZE 7

void environment_startup(void)
{

}

#define SECONDS_IDX 3

asn1SccCucTimestamp getCucTimestamp()
{
   asn1SccCucTimestamp timestamp;
   asn1SccULongInteger nseconds;
   timeservice_PI_ObetTime(&nseconds);
   timeservice_PI_CucTimestamp(&nseconds, &timestamp);

   return timestamp;
}

void environment_PI_Trigger(void)
{
   asn1SccULongInteger nseconds;
   timeservice_PI_ObetTime(&nseconds);
   LOG_VARIABLE_ENDL("Nanoseconds from start: ", nseconds);

   asn1SccCucTimestamp cucTimestamp = getCucTimestamp();
   LOG_VARIABLE_ENDL("CUC timestamp: ", cucTimestamp);

   LOG("\n");
}
