/* Body file for function mmi
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "mmi.h"

void mmi_startup(void)
{
}

void mmi_PI_tm
      (const asn1SccTMPacket *IN_p1)

{
}


