/* Body file for function Client1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "client1.h"
#include <stdio.h>

typedef enum {
    SUBSCRIBE,
    CHECK_CREATE_1,
    CHECK_CREATE_2,
    CHECK_CREATE_3,
    CHECK_CREATE_4,
    CHECK_CREATE_5,
    CHECK_STORE_REJECT,
    FINISHED
} Client1State;

static Client1State state;

static asn1SccDataStoreCreateRequest create_request;

static int create_1_ok;
static int create_2_ok;
static int create_3_ok;
static int create_4_ok;
static int create_5_ok;
static int store_rejected_ok;

void client1_startup(void)
{
    state = SUBSCRIBE;
    create_1_ok = 0;
    create_2_ok = 0;
    create_3_ok = 0;
    create_4_ok = 0;
    create_5_ok = 0;
    store_rejected_ok = 0;
}

void client1_PI_Trigger(void)
{
    asn1SccT_Boolean should_notify = 1;
    switch(state)
    {
    case SUBSCRIBE:
        printf("Checking DataStore with configured size, max 5 items\n");
        client1_RI_subscribe_to_event(&event_id_datastore_notify, &should_notify);
        printf("Subscribed\n");
        fflush(stdout);
        state = CHECK_CREATE_1;
        break;

    case CHECK_CREATE_1:
        printf("Checking create 1\n");
        fflush(stdout);
        create_request.behaviour = DataStoreCreateRequest_behaviour_reject_when_overflow;
        create_request.item_value.kind = DataStoreValueType_coefficient_PRESENT;
        create_request.item_value.u.coefficient = 1;
        client1_RI_Create(&create_request);
        state = CHECK_CREATE_2;
        break;

    case CHECK_CREATE_2:
        if(!create_1_ok)
        {
            state = FINISHED;
        }
        else
        {
            printf("Checking create 2\n");
            fflush(stdout);
            create_request.behaviour = DataStoreCreateRequest_behaviour_reject_when_overflow;
            create_request.item_value.kind = DataStoreValueType_coefficient_PRESENT;
            create_request.item_value.u.coefficient = 2;
            client1_RI_Create(&create_request);
            state = CHECK_CREATE_3;
        }
        break;

    case CHECK_CREATE_3:
        if(!create_2_ok)
        {
            state = FINISHED;
        }
        else
        {
            printf("Checking create 3\n");
            fflush(stdout);
            create_request.behaviour = DataStoreCreateRequest_behaviour_reject_when_overflow;
            create_request.item_value.kind = DataStoreValueType_coefficient_PRESENT;
            create_request.item_value.u.coefficient = 3;
            client1_RI_Create(&create_request);
            state = CHECK_CREATE_4;
        }
        break;

    case CHECK_CREATE_4:
        if(!create_3_ok)
        {
            state = FINISHED;
        }
        else
        {
            printf("Checking create 4\n");
            fflush(stdout);
            create_request.behaviour = DataStoreCreateRequest_behaviour_reject_when_overflow;
            create_request.item_value.kind = DataStoreValueType_coefficient_PRESENT;
            create_request.item_value.u.coefficient = 4;
            client1_RI_Create(&create_request);
            state = CHECK_CREATE_5;
        }
        break;

    case CHECK_CREATE_5:
        if(!create_4_ok)
        {
            state = FINISHED;
        }
        else
        {
            printf("Checking create 5\n");
            fflush(stdout);
            create_request.behaviour = DataStoreCreateRequest_behaviour_reject_when_overflow;
            create_request.item_value.kind = DataStoreValueType_coefficient_PRESENT;
            create_request.item_value.u.coefficient = 5;
            client1_RI_Create(&create_request);
            state = CHECK_STORE_REJECT;
        }
        break;

    case CHECK_STORE_REJECT:
        if(!create_5_ok)
        {
            state = FINISHED;
        }
        else
        {
            printf("Checking create on full Data Store\n");
            fflush(stdout);
            create_request.behaviour = DataStoreCreateRequest_behaviour_reject_when_overflow;
            create_request.item_value.kind = DataStoreValueType_coefficient_PRESENT;
            create_request.item_value.u.coefficient = 6;
            client1_RI_Create(&create_request);
            state = FINISHED;
        }
        break;

    case FINISHED:
        break;
    }
}

void client1_PI_notify
      (const asn1SccT_EventMessage *IN_eventmessage)

{
   switch(state)
   {
   case SUBSCRIBE:
       break;

   case CHECK_CREATE_1:
       break;

   case CHECK_CREATE_2:
       if(IN_eventmessage->kind != T_EventMessage_item_created_PRESENT)
       {
           printf("Unexpected Data Store behaviour\n");
           fflush(stdout);
           return;
       }
       create_1_ok = 1;
       printf("Item created\n");
       fflush(stdout);
       break;

   case CHECK_CREATE_3:
       if(IN_eventmessage->kind != T_EventMessage_item_created_PRESENT)
       {
           printf("Unexpected Data Store behaviour\n");
           fflush(stdout);
           return;
       }
       create_2_ok = 1;
       printf("Item created\n");
       fflush(stdout);
       break;

   case CHECK_CREATE_4:
       if(IN_eventmessage->kind != T_EventMessage_item_created_PRESENT)
       {
           printf("Unexpected Data Store behaviour\n");
           fflush(stdout);
           return;
       }
       create_3_ok = 1;
       printf("Item created\n");
       fflush(stdout);
       break;

   case CHECK_CREATE_5:
       if(IN_eventmessage->kind != T_EventMessage_item_created_PRESENT)
       {
           printf("Unexpected Data Store behaviour\n");
           fflush(stdout);
           return;
       }
       create_4_ok = 1;
       printf("Item created\n");
       fflush(stdout);
       break;

   case CHECK_STORE_REJECT:
       if(IN_eventmessage->kind != T_EventMessage_item_created_PRESENT)
       {
           printf("Unexpected Data Store behaviour\n");
           fflush(stdout);
           return;
       }
       create_5_ok = 1;
       printf("Item created\n");
       fflush(stdout);
       break;

   case FINISHED:
       if(IN_eventmessage->kind != T_EventMessage_item_store_rejected_PRESENT)
       {
           printf("Unexpected Data Store behaviour\n");
           fflush(stdout);
           return;
       }
       printf("Store rejected as expected\n");
       printf("Test succeed\n");
       fflush(stdout);
       break;
   }
}

void client1_PI_notifyRetrieve
      (const asn1SccT_EventRetrieveMessage *IN_eventmessage)

{
}


