/* Body file for function Controller
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "controller.h"
#include <stdio.h>
#include <stdbool.h>

static asn1SccMatLab_Double i1;
static asn1SccMatLab_Single i2;
static asn1SccMatLab_Int8 i3;
static asn1SccMatLab_Uint8 i4;
static asn1SccMatLab_Int16 i5;
static asn1SccMatLab_Uint16 i6;
static asn1SccMatLab_Int32 i7;
static asn1SccMatLab_Uint32 i8;
static asn1SccMatLab_Boolean i9;
static asn1SccMatLab_Double o1;
static asn1SccMatLab_Single o2;
static asn1SccMatLab_Int8 o3;
static asn1SccMatLab_Uint8 o4;
static asn1SccMatLab_Int16 o5;
static asn1SccMatLab_Uint16 o6;
static asn1SccMatLab_Int32 o7;
static asn1SccMatLab_Uint32 o8;
static asn1SccMatLab_Boolean o9;

void controller_startup(void)
{
}

void controller_PI_trigger(void)
{
    i1 = 625.25;
    i2 = 100.015625;
    i3 = -23;
    i4 = 23;
    i5 = -20000;
    i6 = 7001;
    i7 = 1997;
    i8 = 2022;
    i9 = false;

    controller_RI_interfaceBasic(&i1, &i2, &i3, &i4, &i5,
                                 &i6, &i7, &i8, &i9, &o1,
                                 &o2, &o3, &o4, &o5, &o6,
                                 &o7, &o8, &o9);

    if(i1 == o1 && i2 == o2 && i3 == o3 && i4 == o4 &&
       i5 == o5 && i6 == o6 && i7 == o7 && i8 == o8 && i9 == o9)
    {
        printf("Test: OK\n");
    }
    else
    {
        printf("ERROR\n");
    }
}


