/* Body file for function Manager
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "manager.h"

#include <rtems/bspIo.h>
#include <bsp/watchdog.h>
#include <CbiPartitionApi.h>

void print_rtems(const char *str)
{
    while (*str != '\0')
    {
        rtems_putc(*(str++));
    }
}

static void startup_on_processor_reset()
{
    print_rtems("Manager starting up on processor reset\n");
}

static void startup_on_power_reset()
{
    print_rtems("Manager starting up on power reset\n");
}

void manager_startup(void)
{
    print_rtems("Initialization\n");
    Reset_Reason reason = Cbi_Partition_Api_getResetReason();
    switch (reason)
    {
    case Reset_Reason_Power:
        print_rtems("ResetReason: POWER\n");
        startup_on_power_reset();
        return;
    case Reset_Reason_Reset:
        print_rtems("ResetReason: RESET\n");
        startup_on_processor_reset();
        return;
    case Reset_Reason_Unknown:
        print_rtems("ResetReason: UNKNOWN\n");
        break;
    }
}

void manager_PI_r1(void)
{
    // NOP - dummy interface
}

void manager_PI_trigger(void)
{
    print_rtems("Inducing software failure\n");
    bsp_watchdog_system_reset();
}
