/* Body file for function Controller
 * Generated by TASTE on 2022-08-17 10:28:13
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Trigger
 * Required interfaces : Iface
 * User-defined properties for this function:
 * Timers              : 
 */

#include "controller.h"
#include <assert.h>
#include <string.h>

void controller_startup(void)
{
}

void controller_PI_Trigger(void)
{
    asn1SccMyIA5String input = "abcde";
    asn1SccMyIA5String expectedOutput = "bcdef";
    asn1SccMyIA5String output;
    controller_RI_Iface(&input, &output);
    printf("output: %s\n", output);
    assert(strcmp(output, expectedOutput) == 0);
}
