/* Header file for function MMI
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void mmi_startup(void);

/* Provided interfaces */
void mmi_PI_Poll( void );


void mmi_PI_TM( const asn1SccT_Telemetry * );

/* Required interfaces */
extern void mmi_RI_TC( const asn1SccT_Telecommand * );


#ifdef __cplusplus
}
#endif

