/* Body file for function Dst1
 * Generated by TASTE on 2022-08-18 16:30:09
 * You can edit this file, it will not be overwritten
 * Provided interfaces : con1
 * Required interfaces : reply1
 * User-defined properties for this function:
 * Timers              : 
 */

#include "dst1.h"
#include <stdio.h>
#include "routing.h"

void dst1_startup(void)
{

}

void dst1_PI_con1
      (const asn1SccT_Int32 *IN_p1)

{
    if((dst1_con1_get_sender() == PID_src1 && *IN_p1 == 42) ||
       (dst1_con1_get_sender() == PID_src2 && *IN_p1 == 1969) ||
       (dst1_con1_get_sender() == PID_src3 && *IN_p1 == 3000))
    {
        dst1_RI_reply1();
    }
    else
    {
        printf("ERROR\n");
    }
}


