/* Body file for function electrics_power_supply
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "electrics_power_supply.h"
//#include <stdio.h>


void electrics_power_supply_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[electrics_power_supply] Startup");
}

void electrics_power_supply_PI_flow_changed
      (const asn1SccAuroraReal *IN_rate)

{
   // Write your code here
}


void electrics_power_supply_PI_get_battery_capacity
      (asn1SccAuroraBatteryCapacity *OUT_capacity)

{
   // Write your code here
}


void electrics_power_supply_PI_get_solar_panel_status
      (asn1SccAuroraVoltage *OUT_voltage,
       asn1SccAuroraCurrent *OUT_current)

{
   // Write your code here
}


void electrics_power_supply_PI_set_power_point
      (const asn1SccAuroraPWM *IN_pwm)

{
   // Write your code here
}


void electrics_power_supply_PI_step(void)
{
   // Write your code here
}


