/* Body file for function electrics_power_supply
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "electrics_power_supply.h"
//#include <stdio.h>

static double flow_rate_value;
static double battery_capacity;
static double solar_panel_voltage;
static double solar_panel_current;
static double solar_panel_pwm;

void electrics_power_supply_startup(void)
{
    flow_rate_value = 0.0;
    battery_capacity = 0.28;
    solar_panel_voltage = 9.3;
    solar_panel_current = 1.3;
    solar_panel_pwm = 0.0;
}

void electrics_power_supply_PI_flow_changed
      (const asn1SccAuroraReal *IN_rate)

{
   flow_rate_value = *IN_rate;
}


void electrics_power_supply_PI_get_battery_capacity
      (asn1SccAuroraBatteryCapacity *OUT_capacity)

{
   *OUT_capacity = battery_capacity;
}


void electrics_power_supply_PI_get_solar_panel_status
      (asn1SccAuroraVoltage *OUT_voltage,
       asn1SccAuroraCurrent *OUT_current)

{
   *OUT_voltage = solar_panel_voltage;
   *OUT_current = solar_panel_current;
}


void electrics_power_supply_PI_set_power_point
      (const asn1SccAuroraPWM *IN_pwm)

{
   solar_panel_pwm = *IN_pwm;
}


void electrics_power_supply_PI_step(void)
{
   // Write your code here
}


