/* Body file for function Component
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/

#include "component.h"
#include <stdio.h>

static int counter;
static asn1SccPowerMode mode;

void component_startup(void)
{
    counter = 0;
    mode = PowerMode_off;
}

void component_PI_trigger(void)
{
    switch(mode)
    {
        case PowerMode_on:
        {
            printf("Component::mode = on\n");
            counter++;
            printf("Component::counter = %d\n", counter);
            break;
        }
        case PowerMode_off:
        {
            printf("Component::mode = off\n");
            break;
        }
        case PowerMode_suspended:
        {
            printf("Component::mode = suspended\n");
            break;
        }
        default:
        {
            printf("ERROR Component::mode = invalid\n");
        }
    }
}

void component_PI_powerOn(void)
{
   if(mode == PowerMode_off)
   {
       counter = 1;
       mode = PowerMode_on;
   }
   else
   {
       printf("ERROR, invalid state transision\n");
   }
}

void component_PI_resume(void)
{
   if(mode == PowerMode_suspended)
   {
       mode = PowerMode_on;
   }
   else
   {
       printf("ERROR, invalid state transision\n");
   }
}


void component_PI_powerOff(void)
{
   counter = 0;
   mode = PowerMode_off;
}


void component_PI_suspend(void)
{
   if(mode == PowerMode_on)
   {
       mode = PowerMode_suspended;
   }
   else
   {
       printf("ERROR, invalid state transision\n");
   }
}


