/* Body file for function payload
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "payload.h"
//#include <stdio.h>


void payload_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[payload] Startup");
}

void payload_PI_get_payload_status
      (asn1SccAuroraTemperature *OUT_temperature,
       asn1SccAuroraFlowRate *OUT_flow_rate)

{
   // Write your code here
}


void payload_PI_set_flow_controller
      (const asn1SccAuroraPWM *IN_pwm)

{
   // Write your code here
}


void payload_PI_step(void)
{
   // Write your code here
}


