/* Body file for function payload
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "payload.h"
//#include <stdio.h>

static double payload_temperature;
static double payload_flow_rate;
static double payload_target_flow_rate;

void payload_startup(void)
{
    payload_temperature = 18.0;
    payload_flow_rate = 4.0;
    payload_target_flow_rate = 20.0;
}

void payload_PI_get_payload_status
      (asn1SccAuroraTemperature *OUT_temperature,
       asn1SccAuroraFlowRate *OUT_flow_rate)

{
   *OUT_temperature = payload_temperature;
   *OUT_flow_rate = payload_flow_rate;
}


void payload_PI_set_flow_controller
      (const asn1SccAuroraPWM *IN_pwm)

{
   payload_target_flow_rate = *IN_pwm;
}


void payload_PI_step(void)
{
   // Write your code here
}


