/* Header file for function Measurer_And_Actuator
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void measurer_and_actuator_startup(void);

/* Provided interfaces */
void measurer_and_actuator_PI_TC( const asn1SccT_Telecommand * );


void measurer_and_actuator_PI_Tick( void );

/* Required interfaces */
extern void measurer_and_actuator_RI_Read_MGM( asn1SccT_B_b_T * );


extern void measurer_and_actuator_RI_Step( const asn1SccT_B_b_T *, const asn1SccT_Omega *, const asn1SccT_Float *, const asn1SccT_Float *, const asn1SccT_Float *, const asn1SccT_MT_Working *, asn1SccT_Control * );


extern void measurer_and_actuator_RI_TM( const asn1SccT_Telemetry * );


extern void measurer_and_actuator_RI_control_MGT( const asn1SccT_Control * );


extern void measurer_and_actuator_RI_get_step( asn1SccT_UInteger32 * );


extern void measurer_and_actuator_RI_set_step( const asn1SccT_UInteger32 * );


#ifdef __cplusplus
}
#endif
