/* Body file for function Function_4
 * Generated by TASTE on 2022-08-26 14:14:35
 * You can edit this file, it will not be overwritten
 * Provided interfaces : PI_1
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 500
 * Timers              : 
 */

#include "function_4.h"
//#include <stdio.h>


void function_4_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   puts ("[Function_4] Startup");
}

void function_4_PI_PI_1(void)
{
   // Write your code here
}

void function_4_PI_reportSomething(void) {

}
