/* Body file for function Function_1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "function_1.h"
//#include <stdio.h>


void function_1_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Function_1] Startup");
}

void function_1_PI_PI_1(void)
{
   // Write your code here
}


void function_1_PI_error(void)
{
   // Write your code here
}


