/* Body file for function SampleFunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "samplefunction.h"
//#include <stdio.h>


void samplefunction_startup(void)
{
}

void samplefunction_PI_Cyclic(void)
{
}


void samplefunction_PI_Interface2(void)
{
}


void samplefunction_PI_Interface4(void)
{
}


void samplefunction_PI_SporadicInterface(void)
{
}


