/* Body file for function EventGenerator2
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "eventgenerator2.h"
#include "event_helper.h"

void eventgenerator2_startup(void)
{
}

void eventgenerator2_PI_trigger2(void)
{
    asn1SccT_EventMessage event;
    event = build_event(2, T_EventMessage_eventType_lowSeverity,
                        "This is message from EventGenerator2");

    eventgenerator2_RI_notify(&event);
}


