/* Body file for function Function_2
 * Generated by TASTE on 2022-10-07 15:26:42
 * You can edit this file, it will not be overwritten
 * Provided interfaces : PI_1
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 1
 * Timers              : 
 */

#include "function_2.h"


void function_2_startup(void)
{
}

void function_2_PI_PI_1(void)
{
    int a;
    int b;
    a = 10;
    b = a + 3;
}


