/* Body file for function Arbiter
 * Generated by TASTE on 2022-08-18 16:30:09
 * You can edit this file, it will not be overwritten
 * Provided interfaces : reply1
 * Required interfaces : 
 * User-defined properties for this function:
 * Timers              : 
 */

#include "arbiter.h"

#include <rtems.h>
#include <rtems/bspIo.h>

int reply1Count;
int reply2Count;
bool finished = false;

void printf(const char *str)
{
  while (*str != '\0') {
    rtems_putc( *(str++));
  }
}

void arbiter_startup(void)
{
    reply1Count = 0;
    reply2Count = 0;
}

void arbiter_PI_reply1
      (const asn1SccT_Int32 *IN_p1)

{
    if (finished)
    {
        return;
    }
    if (*IN_p1 == 42)
    {
        reply1Count++;
        printf("Received reply from set 1\n");
    }
    if (*IN_p1 == 1969)
    {
        reply2Count++;
        printf("Received reply from set 2\n");
    }
    if ((reply1Count == 3) && (reply2Count == 2))
    {
            printf("n2m test - OK\n");
            finished = true;
    }
}


