/* Body file for function Controller
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "controller.h"
//#include <stdio.h>

static int i;

void controller_startup(void)
{
   i = 0;
}

void controller_PI_trigger(void)
{
    if(i == 0)
    {
        controller_RI_start();
    }
    else if(i == 1)
    {
        controller_RI_suspend();
    }
    else if(i == 2)
    {
        controller_RI_resume();
    }
    else if(i == 3)
    {
        controller_RI_stop();
        i = -1;
    }
    i++;
}




