/* Body file for function Controller
 * Generated by TASTE on 2022-08-10 13:32:58
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Trigger
 * Required interfaces : Iface
 * User-defined properties for this function:
 * Timers              : 
 */

#include "controller.h"
#include <stdio.h>
#include <assert.h>

void controller_startup(void)
{
}

void controller_PI_Trigger(void)
{
    asn1SccMyBool inputParam = true;
    asn1SccMyBool outputParam = true;
    asn1SccMyBool expectedOutput = false;
    controller_RI_Iface( &inputParam, &outputParam );
    printf("Output: %u\n", outputParam);
    assert(outputParam == expectedOutput);
}
