/* Body file for function Error_subscriber
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "error_subscriber.h"
#include <stdio.h>

#define SEC_TO_NS(sec) ((sec)*1000000000)

void error_subscriber_startup(void)
{
}

void error_subscriber_PI_Error_receive
      (const asn1SccT_ErrorMessage *IN_errormessage)

{
    uint64_t time = 0;
    uint32_t seconds = 0;
    uint32_t nanoseconds = 0;

    seconds += (uint32_t)IN_errormessage->timestamp.c1 << 24;
    seconds += (uint32_t)IN_errormessage->timestamp.c2 << 16;
    seconds += (uint32_t)IN_errormessage->timestamp.c3 << 8;
    seconds += (uint32_t)IN_errormessage->timestamp.c4;

    nanoseconds += (uint32_t)IN_errormessage->timestamp.f1 << 24;
    nanoseconds += (uint32_t)IN_errormessage->timestamp.f2 << 16;
    nanoseconds += (uint32_t)IN_errormessage->timestamp.f3 << 8;

    time = SEC_TO_NS((uint64_t)seconds) + (uint64_t)nanoseconds;

    printf("Error Received:\n");
    printf("  error id =       %ld\n", IN_errormessage->id);
    printf("  timestamp =      %ld\n", time);
    printf("  function PID =   %d\n", IN_errormessage->function_status.id);
    printf("  error count =    %ld\n", IN_errormessage->function_status.error_count);
    printf("  function state = %d\n\n", (int)IN_errormessage->function_status.state);
}


