/* Header file for function Datastore
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void datastore_startup(void);

/* Provided interfaces */
void datastore_PI_Clean( void );


void datastore_PI_Create( const asn1SccDataStoreCreateRequest * );


void datastore_PI_Delete( const asn1SccDataStoreDeleteRequest * );


void datastore_PI_Retrieve( const asn1SccDataStoreRetrieveRequest * );


void datastore_PI_RetriveByTimeRange( const asn1SccDataStoreRetrieveTimestampRangeRequest * );


void datastore_PI_Update( const asn1SccDataStoreUpdateRequest * );


void datastore_PI_subscribe_to_event( const asn1SccT_UInt32 *, const asn1SccT_Boolean * );

/* Required interfaces */
extern void datastore_RI_CfsTimestamp( const asn1SccULongInteger *, asn1SccCfsTimestamp * );


extern void datastore_RI_CfsTimestampCmp( const asn1SccCfsTimestamp *, const asn1SccCfsTimestamp *, asn1SccComparisonResult * );


extern void datastore_RI_ClockStatus( asn1SccClockStatusEnum * );


extern void datastore_RI_CucTimestamp( const asn1SccULongInteger *, asn1SccCucTimestamp * );


extern void datastore_RI_CucTimestampCmp( const asn1SccCucTimestamp *, const asn1SccCucTimestamp *, asn1SccComparisonResult * );


extern void datastore_RI_ObetTime( asn1SccULongInteger * );


extern void datastore_RI_notify( const asn1SccT_EventMessage * );


extern void datastore_RI_notifyRetrieve( const asn1SccT_EventRetrieveMessage * );


#ifdef __cplusplus
}
#endif
