/* Body file for function EventGenerator1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "eventgenerator1.h"
#include "event_helper.h"

static int counter;

void eventgenerator1_startup(void)
{
    counter = 0;
}

void eventgenerator1_PI_trigger1(void)
{
    asn1SccT_EventMessage event;
    if(counter == 0)
    {
        event = build_event(1, T_EventMessage_eventType_informative, 
                            "This is message from EventGenerator1");
        counter++;
    }
    else
    {
        event = build_event(2, T_EventMessage_eventType_mediumSeverity, 
                            "This is message from EventGenerator1");
        counter = 0;
    }

    eventgenerator1_RI_notify(&event);
}


