/* Body file for function EventListener3
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "eventlistener3.h"
#include "event_helper.h"

void eventlistener3_startup(void)
{
    asn1SccT_UInt32 eventId = 1;
    bool shouldSubscribe = true;
    eventlistener3_RI_subscribe_to_event(&eventId, &shouldSubscribe);
}

void eventlistener3_PI_receive_event
      (const asn1SccT_EventMessage *IN_eventmessage)

{
    print_event(3, IN_eventmessage);
}


