/* Body file for function Publisher2
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "publisher2.h"

void publisher2_startup(void)
{
}

void publisher2_PI_trigger2(void)
{
    asn1SccT_Int32 x;
    x = 1969;

    publisher2_RI_con1(&x);
}


