/* Body file for function Subscriber
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "subscriber.h"
#include <stdio.h>
#include <routing.h>

void subscriber_startup(void)
{
}

void subscriber_PI_con1
      (const asn1SccT_Int32 *IN_p1)

{
    if((subscriber_con1_get_sender() == PID_publisher1 && *IN_p1 == 42) ||
       (subscriber_con1_get_sender() == PID_publisher2 && *IN_p1 == 1969) ||
       (subscriber_con1_get_sender() == PID_publisher3 && *IN_p1 == 3000))
    {
        subscriber_RI_reply1();
    }
    else
    {
        printf("ERROR\n");
    }
}


