/* Body file for function Component2
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "component2.h"
#include <stdio.h>

static asn1SccPowerMode mode;

void component2_startup(void)
{
    mode = PowerMode_off;
}

void component2_PI_powerOff(void)
{
    printf("Shutdown of component 2\n");
    mode = PowerMode_off;
}


void component2_PI_powerOn(void)
{
    if(mode == PowerMode_off)
    {
        printf("Power on of component 2\n");
        mode = PowerMode_on;
    }
    else
    {
        printf("ERROR, invalid state transision\n");
    }
}


void component2_PI_resume(void)
{
}


void component2_PI_suspend(void)
{
}


