/* Body file for function EventGenerator3
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "eventgenerator3.h"
#include "event_helper.h"

static int counter;

void eventgenerator3_startup(void)
{
    counter = 0;
}

void eventgenerator3_PI_trigger3(void)
{
    asn1SccT_EventMessage event;

    if(counter == 0)
    {
        event = build_event(3, T_EventMessage_eventType_highSeverity,
                            "This is message from EventGenerator3");
        counter++;
    }
    else
    {
        event = build_event(4, T_EventMessage_eventType_informative,
                            "This is message from EventGenerator3");
        counter = 0;
    }

    eventgenerator3_RI_notify(&event);
}


