/* Body file for function Publisher1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "publisher1.h"

void publisher1_startup(void)
{
}

void publisher1_PI_trigger1(void)
{
    asn1SccT_Int32 x;
    x = 42;

    publisher1_RI_con1(&x);
}


