/* Body file for function Controller
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "controller.h"

static int counter;

void controller_startup(void)
{
    counter = 0;
}

void controller_PI_trigger(void)
{
    if(counter == 0)
    {
        controller_RI_powerOnComponent3();
        controller_RI_powerOnComponent1();
        controller_RI_powerOnComponent4();
        controller_RI_powerOnComponent2();
        counter++;
    }
    else if(counter == 1)
    {
        controller_RI_powerOffComponent3();
        controller_RI_powerOffComponent1();
        controller_RI_powerOffComponent4();
        controller_RI_powerOffComponent2();
        counter++;
    }
    else
    {
        // stdout must be flushed for file capture
        fflush(stdout);
        // Regular exit does not terminate the program
        // probably waiting on a clean-up operation
        // which is not needed for this test case.
        _Exit(0);
    }
}




