/* Body file for function Client1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "client1.h"
#include <stdio.h>

typedef enum {
    SUBSCRIBE,
    CHECK_CREATE,
    CHECK_RETRIEVE,
    CHECK_LOG_RETRIEVE,
    FINISHED
} Client1State;

static Client1State state;

static asn1SccDataStoreCreateRequest create_request;
static asn1SccDataStoreRetrieveRequest retrieve_request;
static asn1SccT_EventRetrieveLogMessage log_retrieve;

static asn1SccMyInteger test_value;
static asn1SccDataStoreKeyType item_key;
static int create_ok;
static int retrieve_ok;

void client1_startup(void)
{
    state = SUBSCRIBE;
    test_value = 137;
    create_ok = 0;
    retrieve_ok = 0;
}



void client1_PI_Trigger(void)
{
    asn1SccT_Boolean should_notify = 1;
    asn1SccUShortInteger log_index = 0;
    switch(state)
    {
    case SUBSCRIBE:
        client1_RI_subscribe_to_event(&event_id_datastore_notify, &should_notify);
        //printf("Subscribed\n");
        fflush(stdout);
        state = CHECK_CREATE;
        break;
    case CHECK_CREATE:
        //printf("Checking create\n");
        fflush(stdout);
        create_request.item_value.kind = DataStoreValueType_coefficient_PRESENT;
        create_request.item_value.u.coefficient = test_value;
        client1_RI_Create(&create_request);
        state = CHECK_RETRIEVE;
        break;
    case CHECK_RETRIEVE:
        if(!create_ok)
        {
            state = FINISHED;
        }
        else
        {
            //printf("Checking retrieve\n");
            fflush(stdout);
            retrieve_request.item_key = item_key;
            client1_RI_Retrieve(&retrieve_request);
            state = CHECK_LOG_RETRIEVE;
        }
        break;
    case CHECK_LOG_RETRIEVE:
        if(!retrieve_ok)
        {
            state = FINISHED;
        }
        else
        {
            //printf("Checking log retrieve\n");
            fflush(stdout);
            client1_RI_RetrieveLogItem(&log_retrieve, &log_index);

            if(log_retrieve.kind == T_EventRetrieveLogMessage_log_item_PRESENT)
            {
                if(log_retrieve.u.log_item.operation.kind == DataStoreInternalLogItem_operation_item_retrieved_PRESENT)
                {
                    if(log_retrieve.u.log_item.operation.u.item_retrieved == item_key)
                    {
                        //printf("Log retrieve OK\n");
                        fflush(stdout);
                    }
                }
            }
            state = FINISHED;
        }
        break;
    case FINISHED:
        break;
    }
}


void client1_PI_notify
      (const asn1SccT_EventMessage *IN_eventmessage)

{
   if(IN_eventmessage->kind != T_EventMessage_item_created_PRESENT)
   {
       return;
   }
   item_key = IN_eventmessage->u.item_created.item_key;
   create_ok = 1;
   //printf("Create ok\n");
   fflush(stdout);
}


void client1_PI_notifyRetrieve
      (const asn1SccT_EventRetrieveMessage *IN_eventmessage)

{
   if(IN_eventmessage->kind != T_EventRetrieveMessage_item_retrieved_PRESENT)
   {
       return;
   }
   if(IN_eventmessage->u.item_retrieved.item_key != item_key)
   {
       return;
   }
   if(IN_eventmessage->u.item_retrieved.item_value.kind != DataStoreValueType_coefficient_PRESENT)
   {
       return;
   }
   if(IN_eventmessage->u.item_retrieved.item_value.u.coefficient != test_value)
   {
       return;
   }
   retrieve_ok = 1;
   //printf("Retrieve OK\n");
   fflush(stdout);
}


