/* Body file for function Client1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "client1.h"
#include <stdio.h>

typedef enum {
    SUBSCRIBE,
    CHECK_CREATE,
    CHECK_RETRIEVE,
    CHECK_UPDATE,
    CHECK_DELETE,
    WAIT_FOR_RESULT,
    FINISHED
} Client1State;

static Client1State state;

static asn1SccDataStoreCreateRequest create_request;
static asn1SccDataStoreRetrieveRequest retrieve_request;
static asn1SccDataStoreUpdateRequest update_request;
static asn1SccDataStoreDeleteRequest delete_request;

static asn1SccMyInteger test_value;
static asn1SccMyInteger test_second_value;
static asn1SccDataStoreKeyType item_key;
static int create_ok;
static int retrieve_ok;
static int update_ok;
static int delete_ok;

void client1_startup(void)
{
    state = SUBSCRIBE;
    test_value = 137;
    test_second_value = 0;
    create_ok = 0;
    retrieve_ok = 0;
    update_ok = 0;
    delete_ok = 0;
}

void client1_PI_Trigger(void)
{
    asn1SccT_Boolean should_notify = 1;
    switch(state)
    {
    case SUBSCRIBE:
        client1_RI_subscribe_to_event(&event_id_datastore_notify, &should_notify);
        printf("Subscribed\n");
        fflush(stdout);
        state = CHECK_CREATE;
        break;

    case CHECK_CREATE:
        printf("Checking create\n");
        fflush(stdout);
        create_request.item_value.kind = DataStoreValueType_coefficient_PRESENT;
        create_request.item_value.u.coefficient = test_value;
        client1_RI_Create(&create_request);
        state = CHECK_RETRIEVE;
        break;

    case CHECK_RETRIEVE:
        if(!create_ok)
        {
            state = FINISHED;
        }
        else
        {
            printf("Checking retrieve\n");
            fflush(stdout);
            retrieve_request.item_key = item_key;
            client1_RI_Retrieve(&retrieve_request);
            state = CHECK_UPDATE;
        }
        break;

    case CHECK_UPDATE:
        if(!create_ok)
        {
            state = FINISHED;
        }
        else
        {
            printf("Checking update\n");
            fflush(stdout);
            update_request.item_key = item_key;
            update_request.item_value.kind = DataStoreValueType_coefficient_PRESENT;
            update_request.item_value.u.coefficient = test_second_value;
            client1_RI_Update(&update_request);
            state = CHECK_DELETE;
        }
        break;

    case CHECK_DELETE:
        if(!create_ok)
        {
            state = FINISHED;
        }
        else
        {
            printf("Checking delete\n");
            fflush(stdout);
            delete_request.item_key = item_key;
            client1_RI_Delete(&delete_request);
            state = WAIT_FOR_RESULT;
        }
        break;

    case WAIT_FOR_RESULT:
        if(delete_ok)
        {
            printf("test succeed\n");
            fflush(stdout);
        }
        else
        {
            printf("test succeed\n");
            fflush(stdout);
        }
        state = FINISHED;
        break;

    case FINISHED:
        break;
    }
}

void client1_PI_notify
      (const asn1SccT_EventMessage *IN_eventmessage)

{
    if(state == CHECK_RETRIEVE)
    {
        if(IN_eventmessage->kind != T_EventMessage_item_created_PRESENT)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }
        item_key = IN_eventmessage->u.item_created.item_key;
        create_ok = 1;
        printf("Create ok\n");
        fflush(stdout);
    }
    else if(state == CHECK_DELETE)
    {
        if(IN_eventmessage->kind != T_EventMessage_item_updated_PRESENT)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }
        if(IN_eventmessage->u.item_updated.item_key != item_key)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }
        update_ok = 1;
        printf("Update ok\n");
        fflush(stdout);
    }
    else if(state == WAIT_FOR_RESULT)
    {
        if(IN_eventmessage->kind != T_EventMessage_item_deleted_PRESENT)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }
        if(IN_eventmessage->u.item_deleted.item_key != item_key)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }
        delete_ok = 1;
        printf("Delete ok\n");
        fflush(stdout);
    }
}

void client1_PI_notifyRetrieve
      (const asn1SccT_EventRetrieveMessage *IN_eventmessage)

{
    if(state != CHECK_UPDATE)
    {
        printf("Unexpected datastore behaviour\n");
        fflush(stdout);
        state = FINISHED;
        return;
    }
    if(IN_eventmessage->kind != T_EventRetrieveMessage_item_retrieved_PRESENT)
    {
       printf("Unexpected datastore behaviour\n");
       fflush(stdout);
       state = FINISHED;
       return;
    }
    if(IN_eventmessage->u.item_retrieved.item_key != item_key)
    {
       printf("Unexpected datastore behaviour\n");
       fflush(stdout);
       state = FINISHED;
       return;
    }
    if(IN_eventmessage->u.item_retrieved.item_value.kind != DataStoreValueType_coefficient_PRESENT)
    {
       printf("Unexpected datastore behaviour\n");
       fflush(stdout);
       state = FINISHED;
       return;
    }
    if(IN_eventmessage->u.item_retrieved.item_value.u.coefficient != test_value)
    {
       printf("Unexpected datastore behaviour\n");
       fflush(stdout);
       state = FINISHED;
       return;
    }
    retrieve_ok = 1;
    printf("Retrieve OK\n");
    fflush(stdout);
}


