/* Header file for function controller
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void controller_startup(void);

/* Provided interfaces */
void controller_PI_step( void );

/* Required interfaces */
extern void controller_RI_calculate_mppt( const asn1SccAuroraVoltage *, const asn1SccAuroraCurrent *, asn1SccAuroraPWM * );


extern void controller_RI_calculate_pid( asn1SccAuroraPWM *, const asn1SccAuroraPIDValue *, const asn1SccAuroraPIDValue *, const asn1SccAuroraPIDValue *, const asn1SccAuroraReal *, const asn1SccAuroraReal * );


extern void controller_RI_controller_status( const asn1SccAuroraControllerStatus * );


extern void controller_RI_get_battery_capacity( asn1SccAuroraBatteryCapacity * );


extern void controller_RI_get_payload_status( asn1SccAuroraTemperature *, asn1SccAuroraFlowRate * );


extern void controller_RI_get_solar_panel_status( asn1SccAuroraVoltage *, asn1SccAuroraCurrent * );


extern void controller_RI_set_flow_controller( const asn1SccAuroraPWM * );


extern void controller_RI_set_power_point( const asn1SccAuroraPWM * );


#ifdef __cplusplus
}
#endif
