/* Body file for function Environment
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "environment.h"
#include "logs.h"

void environment_startup(void)
{

}

void environment_PI_Trigger()
{
   asn1SccULongInteger nseconds;
   timeservice_PI_ObetTime(&nseconds);
   LOG_VARIABLE_ENDL("Nanoseconds from start: ", nseconds);
}
