/* Body file for function Client1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "client1.h"
#include <stdio.h>

typedef enum {
    SUBSCRIBE,
    CHECK_CREATE,
    CHECK_RETRIEVE_EXIST,
    CHECK_CLEAN,
    CHECK_RETRIEVE_MISSING,
    WAIT_FOR_RESULTS,
    FINISHED
} Client1State;

static Client1State state;

static asn1SccDataStoreCreateRequest create_request;
static asn1SccDataStoreRetrieveRequest retrieve_request;

static asn1SccMyInteger test_value;
static asn1SccDataStoreKeyType item_key;
static int create_ok;
static int retrieve_exist_ok;
static int clean_ok;
static int retrieve_missing_ok;

void client1_startup(void)
{
    state = SUBSCRIBE;
    test_value = 137;
    create_ok = 0;
    retrieve_exist_ok = 0;
    clean_ok = 0;
    retrieve_missing_ok = 0;
}

void client1_PI_Trigger(void)
{
    asn1SccT_Boolean should_notify = 1;

    switch(state)
    {
    case SUBSCRIBE:
        client1_RI_subscribe_to_event(&event_id_datastore_notify, &should_notify);
        printf("Subscribed\n");
        fflush(stdout);
        state = CHECK_CREATE;
        break;
    case CHECK_CREATE:
        printf("Checking create\n");
        fflush(stdout);
        create_request.item_value.kind = DataStoreValueType_coefficient_PRESENT;
        create_request.item_value.u.coefficient = test_value;
        client1_RI_Create(&create_request);
        state = CHECK_RETRIEVE_EXIST;
        break;
    case CHECK_RETRIEVE_EXIST:
        if(!create_ok)
        {
            state = FINISHED;
        }
        else
        {
            printf("Checking retrieve\n");
            fflush(stdout);
            retrieve_request.item_key = item_key;
            client1_RI_Retrieve(&retrieve_request);
            state = CHECK_CLEAN;
        }
        break;
    case CHECK_CLEAN:
        if(!retrieve_exist_ok)
        {
            state = FINISHED;
        }
        else
        {
            printf("Checking data store clean\n");
            fflush(stdout);
            client1_RI_Clean();
            state = CHECK_RETRIEVE_MISSING;
        }
        break;
    case CHECK_RETRIEVE_MISSING:
        if(!clean_ok)
        {
            state = FINISHED;
        }
        else
        {
            printf("Checking retrieve, expecting error\n");
            fflush(stdout);
            retrieve_request.item_key = item_key;
            client1_RI_Retrieve(&retrieve_request);
            state = WAIT_FOR_RESULTS;
        }
        break;
    case WAIT_FOR_RESULTS:
        if(!retrieve_missing_ok)
        {
            printf("test failed\n");
            fflush(stdout);
        }
        else
        {
            printf("test succeed\n");
            fflush(stdout);
        }
        state = FINISHED;
        break;
    case FINISHED:
        break;
    }
}


void client1_PI_notify
      (const asn1SccT_EventMessage *IN_eventmessage)

{
    if(state == CHECK_RETRIEVE_EXIST)
    {
        if(IN_eventmessage->kind != T_EventMessage_item_created_PRESENT)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }

        item_key = IN_eventmessage->u.item_created.item_key;
        create_ok = 1;
        printf("Create ok\n");
        fflush(stdout);
    }
    else if(state == CHECK_RETRIEVE_MISSING)
    {
        if(IN_eventmessage->kind != T_EventMessage_data_store_cleaned_PRESENT)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }
        clean_ok = 1;
        printf("Clean ok\n");
        fflush(stdout);
    }
    else
    {
        printf("Unexpected datastore behaviour\n");
        fflush(stdout);
        state = FINISHED;
    }
}

void client1_PI_notifyRetrieve
      (const asn1SccT_EventRetrieveMessage *IN_eventmessage)

{
    if(state == CHECK_CLEAN)
    {
        if(IN_eventmessage->kind != T_EventRetrieveMessage_item_retrieved_PRESENT)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }
        if(IN_eventmessage->u.item_retrieved.item_key != item_key)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }
        if(IN_eventmessage->u.item_retrieved.item_value.kind != DataStoreValueType_coefficient_PRESENT)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }
        if(IN_eventmessage->u.item_retrieved.item_value.u.coefficient != test_value)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }
        retrieve_exist_ok = 1;
        printf("Retrieve ok\n");
        fflush(stdout);
    }
    else if(state == WAIT_FOR_RESULTS)
    {
        if(IN_eventmessage->kind != T_EventRetrieveMessage_data_store_error_PRESENT)
        {
            printf("Unexpected datastore behaviour\n");
            fflush(stdout);
            state = FINISHED;
            return;
        }
        retrieve_missing_ok = 1;
        printf("Expected error on retrieve\n");
        fflush(stdout);
    }
    else
    {
        printf("Unexpected datastore behaviour\n");
        fflush(stdout);
        state = FINISHED;
    }
}


