/* Body file for function Dst1
 * Generated by TASTE on 2022-08-18 16:30:09
 * You can edit this file, it will not be overwritten
 * Provided interfaces : con1
 * Required interfaces : reply1
 * User-defined properties for this function:
 * Timers              : 
 */

#include "dst1.h"

void dst1_startup(void)
{

}

void dst1_PI_con1
      (const asn1SccT_Int32 *IN_p1)

{
   dst1_RI_reply1(IN_p1);
}


