/* Body file for function Controller
 * Generated by TASTE on 2022-08-10 13:45:56
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Trigger
 * Required interfaces : Iface
 * User-defined properties for this function:
 * Timers              : 
 */

#include "controller.h"
#include <stdio.h>
#include <assert.h>


void controller_startup(void)
{
}

void controller_PI_Trigger(void)
{
    asn1SccMySeqOf inputParam = { .arr = {3, 5, 7} };
    asn1SccMySeqOf outputParam = { .arr = {0, 0, 0} };
    asn1SccMySeqOf expectedOutput = { .arr = {6, 10, 14} };
    controller_RI_Iface( &inputParam, &outputParam );
    printf("Output: %lu %lu %lu\n", outputParam.arr[0], outputParam.arr[1], outputParam.arr[2]);
    assert(outputParam.arr[0] == expectedOutput.arr[0]);
    assert(outputParam.arr[1] == expectedOutput.arr[1]);
    assert(outputParam.arr[2] == expectedOutput.arr[2]);
}
