/* ASN.1 System configuration file for function algorithms
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/system_config/function.tmplt)
 */
#define __NEED_AuroraVoltage_NATIVE
#define __NEED_AuroraCurrent_NATIVE
#define __NEED_AuroraPWM_NATIVE


#define __NEED_AuroraPWM_NATIVE
#define __NEED_AuroraPIDValue_NATIVE
#define __NEED_AuroraPIDValue_NATIVE
#define __NEED_AuroraPIDValue_NATIVE
#define __NEED_AuroraReal_NATIVE
#define __NEED_AuroraReal_NATIVE

