/* Body file for function TimeService
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/

#include "timeservice.h"
#include "timeservice-api.h"

static TimeService time_service;

void timeservice_startup(void)
{
   TimeService_Startup(&time_service);
}

void timeservice_PI_ObetTime(asn1SccULongInteger *nanoseconds)
{
   *nanoseconds = TimeService_ObetTime(&time_service);
}
