/* Header file for function TimeService
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void timeservice_startup(void);

/* Provided interfaces */
void timeservice_PI_ObetTime( asn1SccULongInteger * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
