/* Header file for function Client1
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void client1_startup(void);

/* Provided interfaces */
void client1_PI_Trigger( void );


void client1_PI_notify( const asn1SccT_EventMessage * );


void client1_PI_notifyRetrieve( const asn1SccT_EventRetrieveMessage * );

/* Required interfaces */
extern void client1_RI_Clean( void );


extern void client1_RI_Create( const asn1SccDataStoreCreateRequest * );


extern void client1_RI_Delete( const asn1SccDataStoreDeleteRequest * );


extern void client1_RI_Retrieve( const asn1SccDataStoreRetrieveRequest * );


extern void client1_RI_RetriveByTimeRange( const asn1SccDataStoreRetrieveTimestampRangeRequest * );


extern void client1_RI_Update( const asn1SccDataStoreUpdateRequest * );


extern void client1_RI_subscribe_to_event( const asn1SccT_UInt32 *, const asn1SccT_Boolean * );


#ifdef __cplusplus
}
#endif
