/* Body file for function Function_1
 * Generated by TASTE on 2022-10-07 15:57:49
 * You can edit this file, it will not be overwritten
 * Provided interfaces : PI_1, PI_2, PI_3
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 1
 * Timers              : 
 */

#include "function_1.h"


void function_1_startup(void)
{
}

void function_1_PI_PI_1(void)
{
    int a;
    int b;
    a = 10;
    b = a + 3;
}


void function_1_PI_PI_2(void)
{
    uint64_t volatile fact = 0;
    uint64_t volatile test_data_1 = 1;
    uint64_t volatile test_data_2 = 100;
    do
    {
        if(test_data_1 < test_data_2)
        {
            fact++;
        }
    } while(fact <= 50000);
}


