/* Body file for function Function_1
 * Generated by TASTE on 2022-08-26 14:14:35
 * You can edit this file, it will not be overwritten
 * Provided interfaces : PI_1
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Startup_Priority = 1
 * Timers              : 
 */

#include "function_1.h"
#include <stdio.h>


void function_1_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   puts ("[Function_1] Startup");
}

void function_1_PI_PI_1(void)
{
    printf("startup-priority test - OK\n");
    // stdout must be flushed for file capture
    fflush(stdout);
    // Regular exit does not terminate the program
    // probably waiting on a clean-up operation
    // which is not needed for this test case.
    _Exit(0);
}


