/* Body file for function Function_1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "function_1.h"
#include <stdlib.h>
#include <time.h>

asn1SccTestMessage buildMessage(const uint32_t data)
{
    asn1SccTestMessage message;
    message.id = (asn1SccMyInteger)(rand() % 10000);
    message.data = (asn1SccMyInteger)data;
    message.validity = TestMessage_validity_valid;
    return message;
}

void function_1_startup(void)
{
   srand(time(NULL));
}

void function_1_PI_trigger(void)
{
    asn1SccTestMessage message = buildMessage(1960);
    function_1_RI_PI_1(&message);
}




