/* Body file for function Subscriber3
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "subscriber3.h"
#include <stdio.h>
#include "routing.h"


void subscriber3_startup(void)
{

}

void subscriber3_PI_con1
      (const asn1SccT_Int32 *IN_p1)

{
    if(subscriber3_con1_get_sender() == PID_publisher && *IN_p1 == 42)
    {
        subscriber3_RI_reply1();
    }
    else
    {
        printf("ERROR\n");
    }
}


