/* Body file for function Src2
 * Generated by TASTE on 2022-08-18 16:30:09
 * You can edit this file, it will not be overwritten
 * Provided interfaces : trigger2
 * Required interfaces : con1
 * User-defined properties for this function:
 * Timers              : 
 */

#include "src2.h"

void src2_startup(void)
{
}

void src2_PI_trigger2(void)
{
    asn1SccT_Int32 x;
    x = 1969;

    src2_RI_con1(&x);
}


