/* Body file for function Environment
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "client1.h"
#include "routing.h"

static asn1SccDataStoreCreateRequest create_request;

static int counter;
static int subscribed;

void client1_startup(void)
{
    counter = 0;
    subscribed = 0;
}

void client1_PI_Trigger( void )
{
    create_request.behaviour = DataStoreCreateRequest_behaviour_free_existing;
    create_request.item_value.kind = DataStoreValueType_coefficient_PRESENT;
    create_request.item_value.u.coefficient = 42;
    printf("Custom value of custom type: %d\n", create_request.item_value.u.coefficient);
    fflush(stdout);
}

void client1_PI_notify( const asn1SccT_EventMessage * ev)
{

}

void client1_PI_notifyRetrieve(const asn1SccT_EventRetrieveMessage* ev)
{

}
