/* Body file for function OtherSampleFunction
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "othersamplefunction.h"
//#include <stdio.h>


void othersamplefunction_startup(void)
{
}

void othersamplefunction_PI_CyclicDefault(void)
{
}


void othersamplefunction_PI_Interface1(void)
{
}


void othersamplefunction_PI_Interface3(void)
{
}


void othersamplefunction_PI_Interface5(void)
{
}


void othersamplefunction_PI_UnprotectedInterface(void)
{
}


