/* Body file for function Publisher3
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the .ads file.   !!
*/
#include "publisher3.h"

void publisher3_startup(void)
{
}

void publisher3_PI_trigger3(void)
{
    asn1SccT_Int32 x;
    x = 3000;

    publisher3_RI_con1(&x);
}


