/* Body file for function controller
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "controller_vm_if.h"
#include "dataview-uniq.h"  // contains definition of PID type
#include <stdio.h>
extern long long getTimeInMilliseconds(void);

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void controller_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}




extern void init_algorithms(void);
extern unsigned algorithms_initialized;
extern void init_algorithms(void);
extern unsigned algorithms_initialized;
extern void init_electrics_power_supply(void);
extern unsigned electrics_power_supply_initialized;
extern void init_payload(void);
extern unsigned payload_initialized;
extern void init_electrics_power_supply(void);
extern unsigned electrics_power_supply_initialized;
unsigned controller_initialized = 0;
void init_controller(void)
{
   if (0 == controller_initialized) {
      // Initialize epoch for the MSC tracing in debug mode
      long long unused = getTimeInMilliseconds();
      controller_initialized = 1;
      // Call user code startup function
      extern void controller_startup(void);
      controller_startup();
      puts ("[TASTE] Initialization completed for function controller");
      controller_initialized = 2;
   }
}
void controller_step(void)
{
   sender_pid = controller_step_get_sender();
   // In Debug mode and x86 builts only: log MSC data when environment variable is set
   static int innerMsc = -1;
   if (-1 == innerMsc)
     innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
   if (1 == innerMsc) {
      long long msc_time = getTimeInMilliseconds();
      printf ("INNER_PI: controller,step,%lld\n", msc_time);
      fflush(stdout);
   }

   //  Directly call user code, no parameters to pass
   extern void controller_PI_step(void);
   controller_PI_step();
   // puts ("controller_step called");
}

