/* Body file for function Controller
 * Generated by TASTE on 2022-08-12 12:13:54
 * You can edit this file, it will not be overwritten
 * Provided interfaces : Trigger
 * Required interfaces : Iface
 * User-defined properties for this function:
 * Timers              : 
 */

#include "controller.h"
#include <stdio.h>
#include <assert.h>

void controller_startup(void)
{
}

void controller_PI_Trigger(void)
{
    asn1SccMySeq inputParam;
    inputParam.intSeqElement = 2;
    inputParam.realSeqElement = 4.0;
    inputParam.boolSeqElement = false;

    asn1SccMySeq outputParam;
    outputParam.intSeqElement = 0;
    outputParam.realSeqElement = 0.0;
    outputParam.boolSeqElement = false;

    asn1SccMySeq expectedOutput;
    expectedOutput.intSeqElement = 4;
    expectedOutput.realSeqElement = 8.0;
    expectedOutput.boolSeqElement = true;

    controller_RI_Iface( &inputParam, &outputParam );
    printf("Output: %lu %f %d\n", outputParam.intSeqElement, outputParam.realSeqElement, outputParam.boolSeqElement);

    assert(outputParam.intSeqElement == expectedOutput.intSeqElement);
    assert(abs(outputParam.realSeqElement - expectedOutput.realSeqElement) < 0.001f);
    assert(outputParam.boolSeqElement == expectedOutput.boolSeqElement);
}
