/* Header file for function Function_1
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void function_1_startup(void);

/* Provided interfaces */
void function_1_PI_Poll( void );

/* Required interfaces */
extern void function_1_RI_PI_1( const asn1SccTestMessage * );


#ifdef __cplusplus
}
#endif

